/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author yefry
 */
public class FrmActCuota extends javax.swing.JFrame {

    /**
     * Creates new form FrmActCuota
     */
    public FrmActCuota() {
        initComponents();
    }
    
    // Método auxiliar para leer un archivo y devolver una lista de líneas
    private java.util.List<String> leerArchivo(java.io.File archivo) throws java.io.IOException {
        java.util.List<String> lineas = new java.util.ArrayList<>();
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                lineas.add(linea);
            }
        }
        return lineas;
    }

    // Método auxiliar para sobreescribir un archivo con una lista actualizada
    private void escribirArchivo(java.io.File archivo, java.util.List<String> lineas) throws java.io.IOException {
        try (java.io.BufferedWriter bw = new java.io.BufferedWriter(new java.io.FileWriter(archivo, false))) { // false para sobreescribir
            for (String linea : lineas) {
                bw.write(linea);
                bw.newLine();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        dateFechaInicial = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        dateFechaFinal = new com.toedter.calendar.JDateChooser();
        btnProcesar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de Actividades");

        btnRegresar.setBackground(new java.awt.Color(204, 153, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Actualizar Cuota");

        btnRegresar1.setBackground(new java.awt.Color(204, 153, 0));
        btnRegresar1.setText("Regresar");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        jLabel31.setText("Fecha Inicial *");

        jLabel32.setText("Fecha Final *");

        btnProcesar.setBackground(new java.awt.Color(0, 153, 0));
        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel31))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btnRegresar1)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dateFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnRegresar1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addComponent(btnProcesar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        java.util.Date utilFechaInicial = dateFechaInicial.getDate();
        java.util.Date utilFechaFinal = dateFechaFinal.getDate();

        if (utilFechaInicial == null || utilFechaFinal == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar ambas fechas.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Formateador para comparar fechas y leer los archivos
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

        try {
            // Cargar todos los archivos en memoria para actualizarlos
            java.io.File fEncabezado = new java.io.File("encabezado_cuota.txt");
            java.io.File fDetalle = new java.io.File("detalle_cuota.txt");
            java.io.File fCobros = new java.io.File("cobros.txt");
            java.io.File fClientes = new java.io.File("clientes.txt");

            if (!fEncabezado.exists() || !fCobros.exists() || !fClientes.exists()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Faltan archivos de datos para procesar.");
                return;
            }

            // Listas para almacenar las líneas y luego reescribir los archivos
            java.util.List<String> listEncabezados = leerArchivo(fEncabezado);
            java.util.List<String> listDetalles = fDetalle.exists() ? leerArchivo(fDetalle) : new java.util.ArrayList<>();
            java.util.List<String> listCobros = leerArchivo(fCobros);
            java.util.List<String> listClientes = leerArchivo(fClientes);

            int cuotasProcesadas = 0;

            // Recorrer los encabezados de cuota
            for (int i = 0; i < listEncabezados.size(); i++) {
                String[] datosEnc = listEncabezados.get(i).split(",", -1);
                if (datosEnc.length < 5) continue;

                String idCuota = datosEnc[0].trim();
                java.util.Date fechaCuota = sdf.parse(datosEnc[1].trim());
                String idCliente = datosEnc[2].trim();
                double totalPagadoCuota = Double.parseDouble(datosEnc[3].trim());
                boolean statusCuota = Boolean.parseBoolean(datosEnc[4].trim());

                // ====================================================================
                // REQUISITO IX: Validar rango de fechas y que Status_Cuota sea false
                // ====================================================================
                boolean enRango = !fechaCuota.before(utilFechaInicial) && !fechaCuota.after(utilFechaFinal);

                if (!statusCuota && enRango) {

                    // ====================================================================
                    // REQUISITO X (Parte 1): Actualizar el Valor_Cobro en el archivo de Cobro
                    // ====================================================================
                    for (String lineaDetalle : listDetalles) {
                        String[] datosDet = lineaDetalle.split(",", -1);
                        if (datosDet[0].trim().equals(idCuota)) {
                            double valorAbonado = Double.parseDouble(datosDet[3].trim());
                            String idCobro = datosDet[4].trim();

                            // Buscar este cobro en listCobros y rebajarle el valor
                            for (int c = 0; c < listCobros.size(); c++) {
                                String[] datosCobro = listCobros.get(c).split(",", -1);
                                if (datosCobro[0].trim().equals(idCobro)) {
                                    double valorActualCobro = Double.parseDouble(datosCobro[3].trim());
                                    valorActualCobro -= valorAbonado;
                                    boolean statusCobro = Boolean.parseBoolean(datosCobro[5].trim());

                                    // "Si el Valor_Cobro queda en Cero se cambia el Status_Cobro a true"
                                    if (valorActualCobro <= 0) {
                                        valorActualCobro = 0;
                                        statusCobro = true;
                                    }

                                    datosCobro[3] = String.valueOf(valorActualCobro);
                                    datosCobro[5] = String.valueOf(statusCobro);
                                    listCobros.set(c, String.join(",", datosCobro));
                                    break; // Ya actualizamos el cobro, pasamos al siguiente detalle
                                }
                            }
                        }
                    }

                    // ====================================================================
                    // REQUISITO X (Parte 2): Actualizar los balances de los clientes
                    // ====================================================================
                    for (int cli = 0; cli < listClientes.size(); cli++) {
                        String[] datosCli = listClientes.get(cli).split(",", -1);
                        if (datosCli[0].trim().equals(idCliente)) {
                            double balanceActual = Double.parseDouble(datosCli[12].trim());
                            balanceActual -= totalPagadoCuota; // Rebajamos lo que pagó
                            if(balanceActual < 0) balanceActual = 0;

                            datosCli[12] = String.valueOf(balanceActual);
                            listClientes.set(cli, String.join(",", datosCli));
                            break; // Ya actualizamos el cliente
                        }
                    }

                    // ====================================================================
                    // REQUISITO XI: Cambiar Status_Cuota a true porque ya se aplicó
                    // ====================================================================
                    datosEnc[4] = "true";
                    listEncabezados.set(i, String.join(",", datosEnc));
                    cuotasProcesadas++;
                }
            }

            if (cuotasProcesadas == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron cuotas pendientes para actualizar en este rango de fechas.", "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Guardar todos los cambios en sus respectivos archivos
            escribirArchivo(fEncabezado, listEncabezados);
            escribirArchivo(fCobros, listCobros);
            escribirArchivo(fClientes, listClientes);

            javax.swing.JOptionPane.showMessageDialog(this, "Proceso finalizado. Se actualizaron " + cuotasProcesadas + " cuotas exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            dateFechaInicial.setDate(null);
            dateFechaFinal.setDate(null);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error durante el procesamiento: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmActCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmActCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmActCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmActCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmActCuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private com.toedter.calendar.JDateChooser dateFechaFinal;
    private com.toedter.calendar.JDateChooser dateFechaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    // End of variables declaration//GEN-END:variables
}
