/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author yefry
 */
public class FrmGenCobro extends javax.swing.JFrame {

    /**
     * Creates new form FrmGenCobro
     */
    public FrmGenCobro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        dateFecha = new com.toedter.calendar.JDateChooser();
        btnProcesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Generar Cobro");

        btnRegresar1.setBackground(new java.awt.Color(204, 153, 0));
        btnRegresar1.setText("Regresar");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        jLabel31.setText("Fecha *");

        btnProcesar.setBackground(new java.awt.Color(0, 153, 0));
        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnRegresar1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel31)
                        .addGap(39, 39, 39)
                        .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnRegresar1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addComponent(btnProcesar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // 1. Obtener la fecha del componente JDateChooser
        java.util.Date fechaSeleccionada = dateFecha.getDate();

        if (fechaSeleccionada == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha válida.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Extraer mes y año de la fecha seleccionada
        java.text.SimpleDateFormat sdfMes = new java.text.SimpleDateFormat("MM");
        java.text.SimpleDateFormat sdfAnio = new java.text.SimpleDateFormat("yyyy");

        String mes = sdfMes.format(fechaSeleccionada);
        String anio = sdfAnio.format(fechaSeleccionada);

        // Concepto para validar si ya se generó
        String conceptoCobro = "Cobro " + mes + "/" + anio;
        java.io.File fileCobros = new java.io.File("cobros.txt");
        java.io.File fileClientes = new java.io.File("clientes.txt");

        // ====================================================================
        // Validar que no se genere el mismo cobro dos veces
        // ====================================================================
        boolean yaGenerado = false;
        if (fileCobros.exists()) {
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(fileCobros))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    // El concepto está en la posición 4 de cobros.txt
                    if (datos.length >= 6 && datos[4].trim().equalsIgnoreCase(conceptoCobro)) {
                        yaGenerado = true;
                        break;
                    }
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error leyendo cobros: " + e.getMessage());
            }
        }

        if (yaGenerado) {
            javax.swing.JOptionPane.showMessageDialog(this, "ERROR: Ya se generaron los cobros para el mes " + mes + " del año " + anio, "Cobro Duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; 
        }

        if (!fileClientes.exists()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El archivo de clientes no existe.");
            return;
        }

        java.util.List<String> clientesActualizados = new java.util.ArrayList<>();
        int cantidadGenerados = 0;

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(fileClientes));
             java.io.BufferedWriter bwCobros = new java.io.BufferedWriter(new java.io.FileWriter(fileCobros, true))) {

            String lineaCliente;
            while ((lineaCliente = br.readLine()) != null) {
                String[] datosCliente = lineaCliente.split(",", -1);

                // Estructura real de clientes.txt (15 campos):
                // 0:Id, 1:Nombre, 2:ApPaterno, 3:ApMaterno, 4:Dir, 5:FecNac, 6:Tel, 7:Cel, 
                // 8:FecIng, 9:Estatus, 10:Tipo, 11:Correo, 12:Balance, 13:ValorCuota, 14:Borrado
                if (datosCliente.length >= 14) {
                    String idCliente = datosCliente[0].trim();
                    String estatus = datosCliente[9].trim();
                    String tipo = datosCliente[10].trim();
                    double balance = Double.parseDouble(datosCliente[12].trim());
                    double valorCuota = Double.parseDouble(datosCliente[13].trim());

                    // Solo procesar Socios Activos
                    if (tipo.equalsIgnoreCase("Socio Activo") && estatus.equalsIgnoreCase("Activo")) {

                        String idCobro = "COB-" + anio + mes + "-" + idCliente; 
                        String fechaGenerada = "30/" + mes + "/" + anio;
                        boolean statusCobro = false;

                        // Guardar en cobros.txt (Id, Fecha, Id_Cliente, Valor, Concepto, Status)
                        bwCobros.write(idCobro + "," + fechaGenerada + "," + idCliente + "," + 
                                       valorCuota + "," + conceptoCobro + "," + statusCobro);
                        bwCobros.newLine();

                        // Actualizar el balance del cliente sumándole el valor de la cuota
                        balance += valorCuota;
                        datosCliente[12] = String.valueOf(balance);

                        cantidadGenerados++;
                    }
                }
                clientesActualizados.add(String.join(",", datosCliente));
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error procesando cobros: " + e.getMessage());
            return;
        }

        // Guardar los balances actualizados en clientes.txt
        try (java.io.BufferedWriter bwClientes = new java.io.BufferedWriter(new java.io.FileWriter(fileClientes))) {
            for (String linea : clientesActualizados) {
                bwClientes.write(linea);
                bwClientes.newLine();
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error actualizando balance de clientes: " + e.getMessage());
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Proceso finalizado exitosamente.\nSe generaron " + cantidadGenerados + " cobros.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        dateFecha.setDate(null);
    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGenCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGenCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGenCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGenCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGenCobro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnRegresar1;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    // End of variables declaration//GEN-END:variables
}
