/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmMovimientoCuota extends javax.swing.JFrame {

    private boolean esNuevaCuota = true;
    private DefaultTableModel modeloTabla;

    public FrmMovimientoCuota() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        modeloTabla = (DefaultTableModel) tblCobros.getModel();
        aplicarEstadoInicial();
    }

    private void aplicarEstadoInicial() {
        // Fecha actual del sistema
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        txtFecha.setText(sdf.format(new Date()));
        
        // Bloquear campos de solo lectura
        txtFecha.setEditable(false);
        txtNombre.setEditable(false);
        
        // ¡CAMBIO AQUÍ! Hacemos que el valor a pagar sea editable para permitir abonos
        txtTotalCuota.setEditable(true); 
        txtTotalCuota.setEnabled(false); // <-- ¡NUEVO CAMBIO AQUÍ! Lo desactivamos al inicio
        
        // Estado inicial de bloqueos
        txtCodCliente.setEnabled(false);
        btnProcesar.setEnabled(false);
        
        // Limpiar
        txtCodCuota.setText("");
        txtCodCliente.setText("");
        txtNombre.setText("");
        txtTotalCuota.setText("0.0");
        modeloTabla.setRowCount(0);
        
        esNuevaCuota = true;
        txtCodCuota.setEnabled(true);
        txtCodCuota.requestFocus();
    }
    
    private void limpiarCampos() {
        // Reutilizar la configuración de estado inicial
        aplicarEstadoInicial();
        
        // Limpiar el campo adicional que no estaba en aplicarEstadoInicial
        txtTotalPendiente.setText("0.0");
    }
    
    private List<String> leerArchivo(String ruta) {
        List<String> lineas = new ArrayList<>();
        File f = new File(ruta);
        if (!f.exists()) return lineas;

        try (BufferedReader br = new BufferedReader(new FileReader(f))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                lineas.add(linea);
            }
        } catch (IOException e) {
            System.out.println("Error leyendo " + ruta);
        }
        return lineas;
    }

    private void escribirArchivo(String ruta, List<String> lineas) throws IOException {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(ruta, false))) {
            for (String linea : lineas) {
                bw.write(linea);
                bw.newLine();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodCuota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTotalCuota = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCobros = new javax.swing.JTable();
        btnProcesar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtTotalPendiente = new javax.swing.JTextField();
        btnLimpiarCampos2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setBackground(new java.awt.Color(204, 153, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Movimiento de Cuotas");

        txtCodCuota.setText("jTextField1");
        txtCodCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodCuotaActionPerformed(evt);
            }
        });

        jLabel8.setText("Cod. Cuota *");

        jLabel9.setText("Fecha");

        txtFecha.setText("jTextField1");
        txtFecha.setEnabled(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel10.setText("Cod. Cliente *");

        txtCodCliente.setText("jTextField1");
        txtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodClienteActionPerformed(evt);
            }
        });

        jLabel11.setText("Nombre *");

        txtNombre.setText("jTextField1");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel12.setText("Valor a Pagar");

        txtTotalCuota.setText("jTextField1");
        txtTotalCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCuotaActionPerformed(evt);
            }
        });

        tblCobros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Cuota", "Sección", "Concepto", "Valor Cuota", "Id Cobro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCobros);

        btnProcesar.setBackground(new java.awt.Color(0, 153, 0));
        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        jLabel13.setText("Total Pendiente");

        txtTotalPendiente.setText("jTextField1");
        txtTotalPendiente.setEnabled(false);
        txtTotalPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPendienteActionPerformed(evt);
            }
        });

        btnLimpiarCampos2.setBackground(new java.awt.Color(0, 153, 255));
        btnLimpiarCampos2.setText("Limpiar Campos");
        btnLimpiarCampos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCampos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnLimpiarCampos2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTotalPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTotalCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegresar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtCodCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotalCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar)
                    .addComponent(btnLimpiarCampos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtCodCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodCuotaActionPerformed
        String idCuota = txtCodCuota.getText().trim();
        if (idCuota.isEmpty()) return;

        File fEncabezado = new File("encabezado_cuota.txt");
        boolean encontrado = false;
        boolean statusCuota = false;
        String idClienteGuardado = "";

        if (fEncabezado.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(fEncabezado))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos[0].trim().equals(idCuota)) {
                        encontrado = true;
                        idClienteGuardado = datos[2].trim();
                        statusCuota = Boolean.parseBoolean(datos[4].trim());
                        break;
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error leyendo encabezado: " + e.getMessage());
            }
        }

        if (encontrado) {
            if (!statusCuota) {
                JOptionPane.showMessageDialog(this, "Modificando", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                esNuevaCuota = false;
                txtCodCliente.setEnabled(true);
                txtCodCliente.setText(idClienteGuardado);
                btnProcesar.setEnabled(true);
                txtCodCuota.setEnabled(false);
                txtCodCliente.requestFocus();
                // Disparar la búsqueda del cliente automáticamente
                txtCodClienteActionPerformed(null); 
            } else {
                JOptionPane.showMessageDialog(this, "Esta cuota ya fue procesada/actualizada. No se puede modificar.", "Error", JOptionPane.ERROR_MESSAGE);
                aplicarEstadoInicial();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Creando", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            esNuevaCuota = true;
            txtCodCliente.setEnabled(true);
            btnProcesar.setEnabled(true);
            txtCodCuota.setEnabled(false);
            txtCodCliente.requestFocus();
        }
    }//GEN-LAST:event_txtCodCuotaActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodClienteActionPerformed
        String idCliente = txtCodCliente.getText().trim();
        if (idCliente.isEmpty()) return;

        // 1. Validar Cliente (Socio y Activo) y obtener Nombre y Balance
        boolean clienteValido = false;
        String nombreCompleto = "";
        String balanceCliente = "0.0";

        try (BufferedReader br = new BufferedReader(new FileReader("clientes.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",", -1);
                if (datos.length >= 13 && datos[0].trim().equals(idCliente)) {
                    // Ajustamos los índices basados en la estructura real del archivo
                    String estado = datos[9].trim();
                    String tipo = datos[10].trim(); 

                    // Usamos .contains para manejar "Socio Activo"
                    if (tipo.toLowerCase().contains("socio") && estado.equalsIgnoreCase("Activo")) {
                        clienteValido = true;
                        String nombre = datos[1].trim();
                        String apellido1 = datos[2].trim();
                        String apellido2 = datos[3].trim();
                        nombreCompleto = nombre + " " + apellido1 + " " + apellido2;

                        // El balance está en la posición 12
                        balanceCliente = datos[12].trim();
                        break;
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error leyendo archivo de clientes: " + e.getMessage());
            return;
        }

        if (!clienteValido) {
            JOptionPane.showMessageDialog(this, "Error: El cliente no existe, no es Socio o no está Activo.", "Validación", JOptionPane.ERROR_MESSAGE);
            txtCodCliente.setText("");
            txtNombre.setText("");
            txtTotalPendiente.setText("0.0");
            modeloTabla.setRowCount(0);
            txtTotalCuota.setText("0.0");
            txtTotalCuota.setEnabled(false); // <-- ¡NUEVO CAMBIO AQUÍ! (Mantenemos bloqueado si falla)
            return;
        }

        // Asignar valores encontrados a los campos correspondientes
        txtNombre.setText(nombreCompleto);
        txtTotalPendiente.setText(balanceCliente);

        // 2. Extraer los cobros de cobros.txt y llenar la tabla exactamente con las 5 columnas del diseño
        modeloTabla.setRowCount(0);
        double totalCuota = 0.0;
        String idCuotaActual = txtCodCuota.getText().trim();

        File fCobros = new File("cobros.txt");
        if (fCobros.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(fCobros))) {
                String linea;
                int seccion = 1;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);

                    // Estructura cobros.txt: 0:Id_Cobro, 1:Fecha, 2:Id_Cliente, 3:Valor, 4:Concepto, 5:Status
                    if (datos.length >= 6 && datos[2].trim().equals(idCliente)) {
                        boolean statusCobro = Boolean.parseBoolean(datos[5].trim());
                        double valorCobro = Double.parseDouble(datos[3].trim());

                        // Solo traer los cobros pendientes (false) y con valor > 0
                        if (!statusCobro && valorCobro > 0) {
                            String idCobro = datos[0].trim();
                            String concepto = datos[4].trim();

                            // Columnas exactas de la tabla: Id Cuota, Sección, Concepto, Valor Cuota, Id Cobro
                            modeloTabla.addRow(new Object[]{idCuotaActual, seccion, concepto, valorCobro, idCobro});
                            totalCuota += valorCobro;
                            seccion++;
                        }
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error leyendo el archivo de cobros: " + e.getMessage());
            }
        }

        txtTotalCuota.setText(String.valueOf(totalCuota));

        if (modeloTabla.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "El socio no tiene cobros pendientes.", "Información", JOptionPane.INFORMATION_MESSAGE);
            btnProcesar.setEnabled(false);
            txtTotalCuota.setEnabled(false); // <-- ¡NUEVO CAMBIO AQUÍ! (Bloqueamos si no hay deudas)
        } else {
            btnProcesar.setEnabled(true);
            txtTotalCuota.setEnabled(true);  // <-- ¡NUEVO CAMBIO AQUÍ! (Activamos para recibir el abono)
            txtTotalCuota.requestFocus();    // <-- ¡NUEVO CAMBIO AQUÍ! (Opcional: Mandamos el cursor de texto directo a este input por comodidad)
        }
    }//GEN-LAST:event_txtCodClienteActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTotalCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCuotaActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        if (modeloTabla.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay detalles para procesar.");
            return;
        }

        String idCuota = txtCodCuota.getText().trim();
        String fecha = txtFecha.getText().trim();
        String idCliente = txtCodCliente.getText().trim();
        String valorCobroTotalStr = txtTotalCuota.getText().trim();
        String statusCuota = "false"; // Nace en false hasta que se salde por completo en otro proceso

        try {
            double abonoCliente = Double.parseDouble(valorCobroTotalStr);

            // 1. Calcular la deuda total actual en la tabla
            double totalDeuda = 0.0;
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                totalDeuda += Double.parseDouble(modeloTabla.getValueAt(i, 3).toString());
            }

            // 2. Validaciones lógicas del abono
            if (abonoCliente <= 0) {
                JOptionPane.showMessageDialog(this, "El valor a pagar debe ser mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (abonoCliente > totalDeuda) {
                JOptionPane.showMessageDialog(this, "El valor a pagar (" + abonoCliente + ") no puede ser mayor a la deuda total (" + totalDeuda + ").", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Distribución del pago en cascada
            double pagoRestante = abonoCliente;
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                double valorDeudaCobro = Double.parseDouble(modeloTabla.getValueAt(i, 3).toString());
                double valorAplicado = 0.0;

                if (pagoRestante >= valorDeudaCobro) {
                    valorAplicado = valorDeudaCobro; // Paga esta fila completa
                    pagoRestante -= valorDeudaCobro;
                } else if (pagoRestante > 0) {
                    valorAplicado = pagoRestante;    // Paga lo que le sobra a esta fila (Abono)
                    pagoRestante = 0;
                } else {
                    valorAplicado = 0.0;             // Ya no queda dinero para esta fila
                }
                
                // Actualizar visualmente la tabla antes de guardar para usar ese valor
                modeloTabla.setValueAt(valorAplicado, i, 3);
            }

            // 4. Leer y limpiar archivos si es modificación
            List<String> listEncabezados = leerArchivo("encabezado_cuota.txt");
            List<String> listDetalles = leerArchivo("detalle_cuota.txt");

            if (!esNuevaCuota) {
                listEncabezados.removeIf(linea -> linea.startsWith(idCuota + ","));
                listDetalles.removeIf(linea -> linea.startsWith(idCuota + ","));
            }

            // 5. Guardar Encabezado con el monto real abonado
            String lineaEncabezado = idCuota + "," + fecha + "," + idCliente + "," + abonoCliente + "," + statusCuota;
            listEncabezados.add(lineaEncabezado);

            // 6. Guardar Detalles (Excluyendo los que quedaron en 0.0)
            int secCuotaReal = 1; 
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                String concepto = modeloTabla.getValueAt(i, 2).toString();
                double valorCuotaAplicado = Double.parseDouble(modeloTabla.getValueAt(i, 3).toString());
                String idCobro = modeloTabla.getValueAt(i, 4).toString();

                // Solo guardamos en detalle_cuota.txt si el cliente realmente le puso dinero a esa factura
                if (valorCuotaAplicado > 0) {
                    String lineaDetalle = idCuota + "," + secCuotaReal + "," + concepto + "," + valorCuotaAplicado + "," + idCobro;
                    listDetalles.add(lineaDetalle);
                    secCuotaReal++;
                }
            }

            escribirArchivo("encabezado_cuota.txt", listEncabezados);
            escribirArchivo("detalle_cuota.txt", listDetalles);

            JOptionPane.showMessageDialog(this, "Proceso completado exitosamente.\nSe registró un pago de: $" + abonoCliente, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            aplicarEstadoInicial();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto numérico válido en 'Valor a Pagar'.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void txtTotalPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPendienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPendienteActionPerformed

    private void btnLimpiarCampos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCampos2ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCampos2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMovimientoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMovimientoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMovimientoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMovimientoCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMovimientoCuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLimpiarCampos;
    public javax.swing.JButton btnLimpiarCampos1;
    public javax.swing.JButton btnLimpiarCampos2;
    public javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCobros;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCodCuota;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTotalCuota;
    private javax.swing.JTextField txtTotalPendiente;
    // End of variables declaration//GEN-END:variables
}
