/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author yefry
 */
public class FrmMantSala extends javax.swing.JFrame {

    // Variable de control
    private boolean esNuevaSala = true;

    // Método que bloquea los botones cuando no hay datos activos
    private void aplicarEstadoInicial() {
        btnGuardar.setEnabled(false);
        btnLimpiarCampos.setEnabled(true); // Cambiado a true para que siempre se pueda reiniciar la vista
        btnEliminar.setEnabled(false);

        // Bloquear campos de edición hasta validar un ID
        setCamposHabilitados(false);

        esNuevaSala = true;
    }

    // Método para limpiar la pantalla y devolverla al estado base
    private void limpiarCampos() {
        txtId.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtIdLocalizacion.setText("");
        
        txtId.requestFocus();
        aplicarEstadoInicial();
    }
    
    private void setCamposHabilitados(boolean habilitar) {
        txtNombre.setEnabled(habilitar);
        txtDescripcion.setEnabled(habilitar);
        txtIdLocalizacion.setEnabled(habilitar);
    }
    
    private void aplicarFiltrosNumericos() {
        // Filtro 1: Solo números enteros (para Código de Cuota y Código de Cliente)
        DocumentFilter filtroEnteros = new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (string != null && string.matches("\\d+")) {
                    super.insertString(fb, offset, string, attr);
                }
            }
            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text != null && text.matches("\\d*")) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        };

        // Aplicar Filtro 1 a los campos de códigos
        ((AbstractDocument) txtId.getDocument()).setDocumentFilter(filtroEnteros);
        ((AbstractDocument) txtIdLocalizacion.getDocument()).setDocumentFilter(filtroEnteros);
    }


    // Constructor de la ventana
    public FrmMantSala() {
        initComponents();
        setLocationRelativeTo(null);
        aplicarFiltrosNumericos(); 
        setTitle("Mantenimiento de Salas");
        
        // --- MAGIA DE FLATLAF: PLACEHOLDERS ---
        txtId.putClientProperty("JTextField.placeholderText", "Ej. 1");
        txtNombre.putClientProperty("JTextField.placeholderText", "Ej. Sala Principal");
        txtDescripcion.putClientProperty("JTextField.placeholderText", "Ej. Sala equipada para pesas y cardio");
        txtIdLocalizacion.putClientProperty("JTextField.placeholderText", "Ej. 10");

        // --- VACIAR LOS CAMPOS PARA QUE SE VEA EL PLACEHOLDER ---
        txtId.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtIdLocalizacion.setText("");

        // --- BLOQUEAR BOTONES AL INICIO ---
        aplicarEstadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnLimpiarCampos = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdLocalizacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de Salas");

        btnRegresar.setBackground(new java.awt.Color(204, 153, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel2.setText("Cod. Sala *");

        txtId.setText("jTextField1");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(0, 153, 255));
        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre  *");

        txtNombre.setText("jTextField1");

        jLabel5.setText("Descripción  *");

        txtDescripcion.setText("jTextField1");

        jLabel3.setText("Cod. Localización *");

        txtIdLocalizacion.setText("jTextField1");
        txtIdLocalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLocalizacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDescripcion))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtId)
                                .addComponent(txtIdLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnLimpiarCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        String idStr = txtId.getText().trim();
        if (idStr.isEmpty()) {
            setCamposHabilitados(false);
            return;
        }

        // Validar que el ID sea un número entero
        try {
            Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de la Sala debe ser un número entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtId.setText("");
            txtId.requestFocus();
            setCamposHabilitados(false);
            return;
        }

        java.io.File archivo = new java.io.File("salas.txt");
        boolean encontrado = false;
        String nombre = "", descripcion = "", idLocalizacion = "", estado = "1";

        if (archivo.exists()) {
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    // Estructura: Id_Sala, Nombre, Descripcion, Id_Localizacion, Estado
                    if (datos.length >= 4 && datos[0].trim().equals(idStr)) {
                        encontrado = true;
                        nombre = datos[1].trim();
                        descripcion = datos[2].trim();
                        idLocalizacion = datos[3].trim();
                        estado = datos.length > 4 ? datos[4].trim() : "1";
                        break;
                    }
                }
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this, "Error al buscar la sala: " + e.getMessage());
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Creando nueva sala...", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            esNuevaSala = true;

            // Desbloquear campos para escritura
            setCamposHabilitados(true);
            btnGuardar.setEnabled(true);
            btnLimpiarCampos.setEnabled(true);
            btnEliminar.setEnabled(false);

            txtNombre.requestFocus();
        } else {
            if (estado.equals("0")) {
                JOptionPane.showMessageDialog(this, "Esta sala se encuentra ELIMINADA/INACTIVA.\nNo es posible modificarla.", "Inactivo", JOptionPane.ERROR_MESSAGE);
                limpiarCampos();
                return;
            }

            JOptionPane.showMessageDialog(this, "Modificando sala existente...", "Aviso", JOptionPane.WARNING_MESSAGE);
            esNuevaSala = false;

            txtNombre.setText(nombre);
            txtDescripcion.setText(descripcion);
            txtIdLocalizacion.setText(idLocalizacion);

            // Desbloquear campos para edición
            setCamposHabilitados(true);
            btnGuardar.setEnabled(true);
            btnLimpiarCampos.setEnabled(true);
            btnEliminar.setEnabled(true);

            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String idStr = txtId.getText().trim();
        String nombre = txtNombre.getText().trim();
        String descripcion = txtDescripcion.getText().trim();
        String idLocStr = txtIdLocalizacion.getText().trim();

        // 1. Validar atributos obligatorios
        if (idStr.isEmpty() || nombre.isEmpty() || descripcion.isEmpty() || idLocStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Integer.parseInt(idLocStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Localización debe ser un número entero válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdLocalizacion.requestFocus();
            return;
        }

        // 2. VALIDAR QUE EL ID DE LOCALIZACIÓN EXISTA EN SU ARCHIVO
        java.io.File archivoLocalizaciones = new java.io.File("localizaciones.txt");
        boolean localizacionExiste = false;

        if (archivoLocalizaciones.exists()) {
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivoLocalizaciones))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    // Asumiendo que localizaciones guarda: Id_Localizacion, Tipo, Estado(opcional)
                    if (datos.length > 0 && datos[0].trim().equals(idLocStr)) {
                        String estadoLoc = datos.length > 2 ? datos[2].trim() : "1";
                        if (estadoLoc.equals("1")) {
                            localizacionExiste = true;
                            break;
                        }
                    }
                }
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this, "Error al verificar la localización: " + e.getMessage());
                return;
            }
        }

        if (!localizacionExiste) {
            JOptionPane.showMessageDialog(this, "El ID de Localización especificado NO existe o se encuentra inactivo en el sistema.", "Error de Referencia", JOptionPane.ERROR_MESSAGE);
            txtIdLocalizacion.requestFocus();
            return;
        }

        // 3. Guardar en salas.txt
        java.io.File archivo = new java.io.File("salas.txt");
        java.util.List<String> lineasArchivo = new java.util.ArrayList<>();

        if (archivo.exists()) {
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                        if (!esNuevaSala) {
                            // Actualiza manteniendo el estado activo (1)
                            lineasArchivo.add(idStr + "," + nombre + "," + descripcion + "," + idLocStr + ",1");
                        }
                    } else {
                        lineasArchivo.add(linea);
                    }
                }
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo de salas: " + e.getMessage());
            }
        }

        if (esNuevaSala) {
            for (String l : lineasArchivo) {
                String[] datos = l.split(",", -1);
                if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                    JOptionPane.showMessageDialog(this, "El ID de esta sala ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            // Agrega nueva sala con estado activo (1)
            lineasArchivo.add(idStr + "," + nombre + "," + descripcion + "," + idLocStr + ",1");
        }

        try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(archivo))) {
            for (String l : lineasArchivo) {
                pw.println(l);
            }
            JOptionPane.showMessageDialog(this, "Sala guardada correctamente.");
            limpiarCampos();
        } catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar sala: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idStr = txtId.getText().trim();
        if (idStr.isEmpty()) return;

        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar la sala ID: " + idStr + "?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) return;

        java.io.File archivo = new java.io.File("salas.txt");
        java.util.List<String> lineasArchivo = new java.util.ArrayList<>();
        boolean encontrado = false;

        if (archivo.exists()) {
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                        String nom = datos.length > 1 ? datos[1].trim() : "";
                        String desc = datos.length > 2 ? datos[2].trim() : "";
                        String idLoc = datos.length > 3 ? datos[3].trim() : "";
                        // Cambiar estado a inactivo (0)
                        lineasArchivo.add(idStr + "," + nom + "," + desc + "," + idLoc + ",0");
                        encontrado = true;
                    } else {
                        lineasArchivo.add(linea);
                    }
                }
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo: " + e.getMessage());
                return;
            }
        }

        if (encontrado) {
            try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(archivo))) {
                for (String l : lineasArchivo) {
                    pw.println(l);
                }
                JOptionPane.showMessageDialog(this, "Sala eliminada lógicamente.");
                limpiarCampos();
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtIdLocalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLocalizacionActionPerformed
        String idLocStr = txtIdLocalizacion.getText().trim();
        if (idLocStr.isEmpty()) return;

        // 1. Validar que sea un número entero
        try {
            Integer.parseInt(idLocStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Localización debe ser un número entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdLocalizacion.setText("");
            txtIdLocalizacion.requestFocus();
            return;
        }

        // 2. Validar inmediatamente si existe y está activo en localizaciones.txt
        java.io.File archivoLocalizaciones = new java.io.File("localizaciones.txt");
        boolean localizacionExiste = false;

        if (archivoLocalizaciones.exists()) {
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivoLocalizaciones))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idLocStr)) {
                        String estadoLoc = datos.length > 2 ? datos[2].trim() : "1";
                        if (estadoLoc.equals("1")) {
                            localizacionExiste = true;
                            break;
                        }
                    }
                }
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this, "Error al verificar la localización: " + e.getMessage());
            }
        }

        if (!localizacionExiste) {
            JOptionPane.showMessageDialog(this, "El ID de Localización ingresado NO existe o se encuentra inactivo.", "Error de Referencia", JOptionPane.ERROR_MESSAGE);
            txtIdLocalizacion.setText("");
            txtIdLocalizacion.requestFocus();
        } else {
            // Si es válido, pasa automáticamente el foco a la descripción
            txtDescripcion.requestFocus();
        }
    }//GEN-LAST:event_txtIdLocalizacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMantSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtIdLocalizacion;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
