/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author yefry
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private int nivelAccesoUsuario;

    // Constructor vacío (por si se abre directamente por pruebas)
    public FrmMenuPrincipal() {
        this(0); // Por defecto entra como Administrador
    }

    // Constructor que recibe el nivel de acceso desde el Login
    public FrmMenuPrincipal(int nivelAcceso) {
        this.nivelAccesoUsuario = nivelAcceso;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menú Principal - Sistema");
        
        // Aplicar control de accesos según el rol
        aplicarRestricciones();
    }

    // Método autónomo para restringir botones según el rol
    private void aplicarRestricciones() {
        if (nivelAccesoUsuario != 0) {
            // Si NO es Administrador, bloqueamos el módulo de mantenimiento de usuarios
            btnMantenimientoUsuarios.setEnabled(false);
            btnMantenimientoUsuarios.setToolTipText("Acceso restringido: Solo para Administradores");
        }
    }                                                     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnMantenimientoUsuarios = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        btnM = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Mantenimientos");

        btnMantenimientoUsuarios.setText("Usuarios");
        btnMantenimientoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoUsuarios);

        jMenuItem2.setText("Entrenador");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Localización");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Salas");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Actividades");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Horarios de Actividades");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Clientes");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Estado de Reservas");
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Reservas");
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText("Reserva de Actividades");
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimientos");

        jMenuItem11.setText("Cuotas");
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Procesos");

        jMenuItem12.setText("Generar Cobro");
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Actualiza Cuota");
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jMenuItem14.setText("Usuarios");
        jMenu4.add(jMenuItem14);

        jMenuItem15.setText("Entrenador");
        jMenu4.add(jMenuItem15);

        jMenuItem16.setText("Localización");
        jMenu4.add(jMenuItem16);

        jMenuItem17.setText("Salas");
        jMenu4.add(jMenuItem17);

        jMenuItem18.setText("Actividades");
        jMenu4.add(jMenuItem18);

        jMenuItem19.setText("Horarios de Actividades");
        jMenu4.add(jMenuItem19);

        jMenuItem20.setText("Cobro por Rango de Fecha");
        jMenu4.add(jMenuItem20);

        jMenuItem21.setText("Cobro por Cliente");
        jMenu4.add(jMenuItem21);

        jMenuItem22.setText("Cuota por Fecha");
        jMenu4.add(jMenuItem22);

        jMenuItem23.setText("Cuota por Clientes");
        jMenu4.add(jMenuItem23);

        jMenuItem24.setText("Clientes");
        jMenu4.add(jMenuItem24);

        jMenuItem25.setText("Clientes con Balance pendiente");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem25);

        jMenuBar1.add(jMenu4);

        btnM.setText("Cerrar Sesión");
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Salir");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        btnM.add(btnCerrarSesion);

        jMenuBar1.add(btnM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMantenimientoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoUsuariosActionPerformed
        new FrmMantUsuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoUsuariosActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        
    }//GEN-LAST:event_btnMActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea cerrar sesión?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                new FrmLogin().setVisible(true); // Vuelve al login
                this.dispose(); // Cierra el menú
            }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenu btnM;
    private javax.swing.JMenuItem btnMantenimientoUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
