/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author yefry
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private int nivelAccesoUsuario;

    // Constructor vacío (por si se abre directamente por pruebas)
    public FrmMenuPrincipal() {
        this(0); // Por defecto entra como Administrador
    }

    // Constructor que recibe el nivel de acceso desde el Login
    public FrmMenuPrincipal(int nivelAcceso) {
        this.nivelAccesoUsuario = nivelAcceso;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menú Principal - Sistema");
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        // Aplicar control de accesos según el rol
        aplicarRestricciones();
    }

    // Método autónomo para restringir botones según el rol
    private void aplicarRestricciones() {
        if (nivelAccesoUsuario != 0) {
            // Si NO es Administrador, bloqueamos el módulo de mantenimiento de usuarios
            btnMantenimientoUsuarios.setEnabled(false);
            btnMantenimientoUsuarios.setToolTipText("Acceso restringido: Solo para Administradores");
            btnGenerarCobro.setEnabled(false);
            btnGenerarCobro.setToolTipText("Acceso restringido: Solo para Administradores");
            btnActualizarCuota.setEnabled(false);
            btnActualizarCuota.setToolTipText("Acceso restringido: Solo para Administradores");
        }
    }                                                     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnMantenimientoUsuarios = new javax.swing.JMenuItem();
        btnMantenimientoEntrenadores = new javax.swing.JMenuItem();
        btnMantenimientoLocalizacion = new javax.swing.JMenuItem();
        btnMantenimientoSalas = new javax.swing.JMenuItem();
        btnMantenimientoActividades = new javax.swing.JMenuItem();
        btnMantenimientoHActividades = new javax.swing.JMenuItem();
        btnMantenimientoClientes = new javax.swing.JMenuItem();
        btnMantenimientoEReservas = new javax.swing.JMenuItem();
        btnMantenimientoReservas = new javax.swing.JMenuItem();
        btnMantenimientoRActividades = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnMoviCuotas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnGenerarCobro = new javax.swing.JMenuItem();
        btnActualizarCuota = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnConUsuarios = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        btnM = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Mantenimientos");

        btnMantenimientoUsuarios.setText("Usuarios");
        btnMantenimientoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoUsuarios);

        btnMantenimientoEntrenadores.setText("Entrenador");
        btnMantenimientoEntrenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoEntrenadoresActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoEntrenadores);

        btnMantenimientoLocalizacion.setText("Localización");
        btnMantenimientoLocalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoLocalizacionActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoLocalizacion);

        btnMantenimientoSalas.setText("Salas");
        btnMantenimientoSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoSalasActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoSalas);

        btnMantenimientoActividades.setText("Actividades");
        btnMantenimientoActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActividadesActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoActividades);

        btnMantenimientoHActividades.setText("Horarios de Actividades");
        btnMantenimientoHActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoHActividadesActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoHActividades);

        btnMantenimientoClientes.setText("Clientes");
        btnMantenimientoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoClientesActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoClientes);

        btnMantenimientoEReservas.setText("Estado de Reservas");
        btnMantenimientoEReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoEReservasActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoEReservas);

        btnMantenimientoReservas.setText("Reservas");
        btnMantenimientoReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoReservasActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoReservas);

        btnMantenimientoRActividades.setText("Reserva de Actividades");
        btnMantenimientoRActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoRActividadesActionPerformed(evt);
            }
        });
        jMenu1.add(btnMantenimientoRActividades);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimientos");

        btnMoviCuotas.setText("Cuotas");
        btnMoviCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoviCuotasActionPerformed(evt);
            }
        });
        jMenu2.add(btnMoviCuotas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Procesos");

        btnGenerarCobro.setText("Generar Cobro");
        btnGenerarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCobroActionPerformed(evt);
            }
        });
        jMenu3.add(btnGenerarCobro);

        btnActualizarCuota.setText("Actualiza Cuota");
        btnActualizarCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCuotaActionPerformed(evt);
            }
        });
        jMenu3.add(btnActualizarCuota);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        btnConUsuarios.setText("Usuarios");
        btnConUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(btnConUsuarios);

        jMenuItem15.setText("Entrenador");
        jMenu4.add(jMenuItem15);

        jMenuItem16.setText("Localización");
        jMenu4.add(jMenuItem16);

        jMenuItem17.setText("Salas");
        jMenu4.add(jMenuItem17);

        jMenuItem18.setText("Actividades");
        jMenu4.add(jMenuItem18);

        jMenuItem19.setText("Horarios de Actividades");
        jMenu4.add(jMenuItem19);

        jMenuItem20.setText("Cobro por Rango de Fecha");
        jMenu4.add(jMenuItem20);

        jMenuItem21.setText("Cobro por Cliente");
        jMenu4.add(jMenuItem21);

        jMenuItem22.setText("Cuota por Fecha");
        jMenu4.add(jMenuItem22);

        jMenuItem23.setText("Cuota por Clientes");
        jMenu4.add(jMenuItem23);

        jMenuItem24.setText("Clientes");
        jMenu4.add(jMenuItem24);

        jMenuItem25.setText("Clientes con Balance pendiente");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem25);

        jMenuBar1.add(jMenu4);

        btnM.setText("Cerrar Sesión");
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Salir");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        btnM.add(btnCerrarSesion);

        jMenuBar1.add(btnM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMantenimientoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoUsuariosActionPerformed
        new FrmMantUsuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoUsuariosActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        
    }//GEN-LAST:event_btnMActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea cerrar sesión?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                new FrmLogin().setVisible(true); // Vuelve al login
                this.dispose(); // Cierra el menú
            }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnMantenimientoEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoEntrenadoresActionPerformed
        new FrmMantEntrenador().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoEntrenadoresActionPerformed

    private void btnMantenimientoLocalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoLocalizacionActionPerformed
        new FrmMantLocalizacion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoLocalizacionActionPerformed

    private void btnMantenimientoSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoSalasActionPerformed
        new FrmMantSala().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoSalasActionPerformed

    private void btnMantenimientoActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActividadesActionPerformed
        new FrmMantActividad().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoActividadesActionPerformed

    private void btnMantenimientoHActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoHActividadesActionPerformed
        new FrmMantHorarioActividad().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoHActividadesActionPerformed

    private void btnMantenimientoEReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoEReservasActionPerformed
        new FrmMantEstadoReserva().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoEReservasActionPerformed

    private void btnMantenimientoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoClientesActionPerformed
        new FrmMantCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoClientesActionPerformed

    private void btnMantenimientoReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoReservasActionPerformed
        new FrmMantReserva().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoReservasActionPerformed

    private void btnMantenimientoRActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoRActividadesActionPerformed
        new FrmMantReservaActividades().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMantenimientoRActividadesActionPerformed

    private void btnGenerarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCobroActionPerformed
        new FrmGenCobro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenerarCobroActionPerformed

    private void btnActualizarCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCuotaActionPerformed
        new FrmActCuota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActualizarCuotaActionPerformed

    private void btnMoviCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoviCuotasActionPerformed
        new FrmMovimientoCuota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMoviCuotasActionPerformed

    private void btnConUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConUsuariosActionPerformed
        new FrmConsultaUsuarios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnActualizarCuota;
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnConUsuarios;
    private javax.swing.JMenuItem btnGenerarCobro;
    private javax.swing.JMenu btnM;
    private javax.swing.JMenuItem btnMantenimientoActividades;
    private javax.swing.JMenuItem btnMantenimientoClientes;
    private javax.swing.JMenuItem btnMantenimientoEReservas;
    private javax.swing.JMenuItem btnMantenimientoEntrenadores;
    private javax.swing.JMenuItem btnMantenimientoHActividades;
    private javax.swing.JMenuItem btnMantenimientoLocalizacion;
    private javax.swing.JMenuItem btnMantenimientoRActividades;
    private javax.swing.JMenuItem btnMantenimientoReservas;
    private javax.swing.JMenuItem btnMantenimientoSalas;
    private javax.swing.JMenuItem btnMantenimientoUsuarios;
    private javax.swing.JMenuItem btnMoviCuotas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    // End of variables declaration//GEN-END:variables
}
