/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author yefry
 */
public class FrmMantHorarioActividad extends javax.swing.JFrame {
    
    private boolean esNuevoHorario = true;

    // Método que bloquea los botones cuando no hay datos activos
    private void aplicarEstadoInicial() {
        btnGuardar.setEnabled(false);
        btnLimpiarCampos.setEnabled(false); 
        btnEliminar.setEnabled(false);
        esNuevoHorario = true;

        // Bloquear campos de edición hasta validar el ID
        setCamposHabilitados(false);
    }

    // Método para limpiar la pantalla y devolverla al estado base
    private void limpiarCampos() {
        txtIdHorarioAct.setText("");
        cmbDiaAct.setSelectedIndex(0);
        txtHoraAct.setText("");
        txtIdActividad.setText("");
        
        txtIdHorarioAct.requestFocus();
        aplicarEstadoInicial();
    }
    
    private void setCamposHabilitados(boolean habilitar) {
        cmbDiaAct.setEnabled(habilitar);
        txtHoraAct.setEnabled(habilitar);
        txtIdActividad.setEnabled(habilitar);
    }

    // Constructor de la ventana
    public FrmMantHorarioActividad() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Mantenimiento de Horarios Actividades");
        
        // --- MAGIA DE FLATLAF: PLACEHOLDERS ---
        txtIdHorarioAct.putClientProperty("JTextField.placeholderText", "Ej. H01");
        txtHoraAct.putClientProperty("JTextField.placeholderText", "Ej. 08:00");
        txtIdActividad.putClientProperty("JTextField.placeholderText", "Ej. 1");

        // --- VACIAR LOS CAMPOS PARA QUE SE VEA EL PLACEHOLDER ---
        txtIdHorarioAct.setText("");
        txtHoraAct.setText("");
        txtIdActividad.setText("");

        // --- BLOQUEAR BOTONES AL INICIO ---
        aplicarEstadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoraAct = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        txtIdActividad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdHorarioAct = new javax.swing.JTextField();
        btnLimpiarCampos = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbDiaAct = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Hora de Actividad *");

        jLabel3.setText("Cod. Actividad *");

        txtHoraAct.setText("jTextField1");
        txtHoraAct.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoraActFocusLost(evt);
            }
        });
        txtHoraAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(204, 153, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        txtIdActividad.setText("jTextField1");
        txtIdActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActividadActionPerformed(evt);
            }
        });

        jLabel2.setText("Cod. Horario Actividad *");

        txtIdHorarioAct.setText("jTextField1");
        txtIdHorarioAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdHorarioActActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(0, 153, 255));
        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Dia de Actividad  *");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de Horario Actividades");

        cmbDiaAct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdHorarioAct)
                            .addComponent(txtIdActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbDiaAct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraAct, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdHorarioAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbDiaAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtHoraAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtIdActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtHoraActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActActionPerformed
        
    }//GEN-LAST:event_txtHoraActActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtIdActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActividadActionPerformed
        String idActStr = txtIdActividad.getText().trim();
        if (idActStr.isEmpty()) return;

        try {
            Integer.parseInt(idActStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Actividad debe ser un número entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdActividad.setText("");
            txtIdActividad.requestFocus();
            return;
        }

        File archivoActividades = new File("actividades.txt");
        boolean actividadExiste = false;

        if (archivoActividades.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivoActividades))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idActStr)) {
                        String estadoAct = datos.length > 5 ? datos[5].trim() : "1";
                        if (estadoAct.equals("1")) {
                            actividadExiste = true;
                            break;
                        }
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al verificar la actividad: " + e.getMessage());
            }
        }

        if (!actividadExiste) {
            JOptionPane.showMessageDialog(this, "El ID de Actividad ingresado NO existe o se encuentra inactivo.", "Error de Referencia", JOptionPane.ERROR_MESSAGE);
            txtIdActividad.setText("");
            txtIdActividad.requestFocus();
        } else {
            btnGuardar.requestFocus();
        }
    }//GEN-LAST:event_txtIdActividadActionPerformed

    private void txtIdHorarioActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdHorarioActActionPerformed
        String idStr = txtIdHorarioAct.getText().trim();
        if (idStr.isEmpty()) {
            setCamposHabilitados(false);
            return;
        }

        File archivo = new File("horarios_actividades.txt");
        boolean encontrado = false;
        String dia = "", hora = "", idAct = "", estado = "1";

        if (archivo.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    // Estructura: Id_Horario_Act, Dia_Act, Hora_Act, Id_Actividad, Estado
                    if (datos.length >= 4 && datos[0].trim().equals(idStr)) {
                        encontrado = true;
                        dia = datos[1].trim();
                        hora = datos[2].trim();
                        idAct = datos[3].trim();
                        estado = datos.length > 4 ? datos[4].trim() : "1";
                        break;
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al buscar el horario de actividad: " + e.getMessage());
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Creando...", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            esNuevoHorario = true;

            // Habilitar campos y botones para nuevo registro
            setCamposHabilitados(true);
            btnGuardar.setEnabled(true);
            btnLimpiarCampos.setEnabled(true);
            btnEliminar.setEnabled(false);

            cmbDiaAct.requestFocus();
        } else {
            if (estado.equals("0")) {
                JOptionPane.showMessageDialog(this, "Este horario de actividad se encuentra ELIMINADO/INACTIVO.\nNo es posible modificarlo.", "Inactivo", JOptionPane.ERROR_MESSAGE);
                limpiarCampos();
                return;
            }

            JOptionPane.showMessageDialog(this, "Modificando...", "Aviso", JOptionPane.WARNING_MESSAGE);
            esNuevoHorario = false;

            cmbDiaAct.setSelectedItem(dia);
            txtHoraAct.setText(hora);
            txtIdActividad.setText(idAct);

            // Habilitar campos y botones para modificación
            setCamposHabilitados(true);
            btnGuardar.setEnabled(true);
            btnLimpiarCampos.setEnabled(true);
            btnEliminar.setEnabled(true);

            cmbDiaAct.requestFocus();
        }
    }//GEN-LAST:event_txtIdHorarioActActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String idHorarioStr = txtIdHorarioAct.getText().trim();
        String dia = cmbDiaAct.getSelectedItem().toString();
        
        // Aplicar formato automático a la hora antes de validar
        formatearHoraAutomatica();
        String horaStr = txtHoraAct.getText().trim();
        
        String idActStr = txtIdActividad.getText().trim();

        // 1. Validar atributos obligatorios
        if (idHorarioStr.isEmpty() || horaStr.isEmpty() || idActStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar formato de hora estricto tipo 00:00 (HH:mm de 24 horas)
        String patronHora = "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$";
        if (!horaStr.matches(patronHora)) {
            JOptionPane.showMessageDialog(this, "La hora debe cumplir con el formato HH:mm (ej. 08:00 o 14:30) y estar en el rango de 00:00 a 23:59.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtHoraAct.requestFocus();
            return;
        }

        try {
            Integer.parseInt(idActStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Actividad debe ser un número entero válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdActividad.requestFocus();
            return;
        }

        // 2. VALIDAR QUE EL ID DE ACTIVIDAD EXISTA Y ESTÉ ACTIVO
        File archivoActividades = new File("actividades.txt");
        boolean actividadExiste = false;

        if (archivoActividades.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivoActividades))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idActStr)) {
                        String estadoAct = datos.length > 5 ? datos[5].trim() : "1";
                        if (estadoAct.equals("1")) {
                            actividadExiste = true;
                            break;
                        }
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al verificar la actividad: " + e.getMessage());
                return;
            }
        }

        if (!actividadExiste) {
            JOptionPane.showMessageDialog(this, "El ID de Actividad especificado NO existe o se encuentra inactivo.", "Error de Referencia", JOptionPane.ERROR_MESSAGE);
            txtIdActividad.requestFocus();
            return;
        }

        // 3. Guardar en horarios_actividades.txt
        File archivo = new File("horarios_actividades.txt");
        List<String> lineasArchivo = new ArrayList<>();

        if (archivo.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idHorarioStr)) {
                        if (!esNuevoHorario) {
                            // Actualiza manteniendo el estado activo (1)
                            lineasArchivo.add(idHorarioStr + "," + dia + "," + horaStr + "," + idActStr + ",1");
                        }
                    } else {
                        lineasArchivo.add(linea);
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo de horarios de actividades: " + e.getMessage());
            }
        }

        if (esNuevoHorario) {
            for (String l : lineasArchivo) {
                String[] datos = l.split(",", -1);
                if (datos.length > 0 && datos[0].trim().equals(idHorarioStr)) {
                    JOptionPane.showMessageDialog(this, "El ID de este horario ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            // Agrega nuevo horario con estado activo (1)
            lineasArchivo.add(idHorarioStr + "," + dia + "," + horaStr + "," + idActStr + ",1");
        }

        try (PrintWriter pw = new PrintWriter(new FileWriter(archivo))) {
            for (String l : lineasArchivo) {
                pw.println(l);
            }
            JOptionPane.showMessageDialog(this, "Horario de actividad guardado correctamente.");
            limpiarCampos();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar horario de actividad: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idStr = txtIdHorarioAct.getText().trim();
        if (idStr.isEmpty()) return;

        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar el horario de actividad ID: " + idStr + "?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) return;

        File archivo = new File("horarios_actividades.txt");
        List<String> lineasArchivo = new ArrayList<>();
        boolean encontrado = false;

        if (archivo.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                        String dia = datos.length > 1 ? datos[1].trim() : "";
                        String hora = datos.length > 2 ? datos[2].trim() : "";
                        String idAct = datos.length > 3 ? datos[3].trim() : "";
                        // Cambiar estado a inactivo (0)
                        lineasArchivo.add(idHorarioStr_Inactivo_Helper(idStr, dia, hora, idAct));
                        encontrado = true;
                    } else {
                        lineasArchivo.add(linea);
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo: " + e.getMessage());
                return;
            }
        }

        if (encontrado) {
            try (PrintWriter pw = new PrintWriter(new FileWriter(archivo))) {
                for (String l : lineasArchivo) {
                    pw.println(l);
                }
                JOptionPane.showMessageDialog(this, "Horario de actividad eliminado lógicamente.");
                limpiarCampos();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtHoraActFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraActFocusLost
        formatearHoraAutomatica();
    }//GEN-LAST:event_txtHoraActFocusLost

    private void formatearHoraAutomatica() {
        String hora = txtHoraAct.getText().trim();
        if (hora.matches("\\d{4}")) {
            txtHoraAct.setText(hora.substring(0, 2) + ":" + hora.substring(2, 4));
        }
    }
    
    private String idHorarioStr_Inactivo_Helper(String idStr, String dia, String hora, String idAct) {
        return idStr + "," + dia + "," + hora + "," + idAct + ",0";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantHorarioActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantHorarioActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantHorarioActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantHorarioActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMantHorarioActividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbDiaAct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField txtHoraAct;
    public javax.swing.JTextField txtIdActividad;
    public javax.swing.JTextField txtIdHorarioAct;
    // End of variables declaration//GEN-END:variables
}
