/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author yefry
 */
public class FrmMantEntrenador extends javax.swing.JFrame {
    
    private boolean esNuevoEntrenador = true;

    // Método que bloquea los botones cuando no hay datos activos
    private void aplicarEstadoInicial() {
        btnGuardar.setEnabled(false);
        btnLimpiarCampos.setEnabled(false);
        btnEliminar.setEnabled(false);
        esNuevoEntrenador = true;

        // Bloquear campos de edición hasta validar el ID
        setCamposHabilitados(false);
    }

    // Método para limpiar la pantalla y devolverla al estado base
    private void limpiarCampos() {
        txtId.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        
        txtId.requestFocus();
        aplicarEstadoInicial();
    }
    
    private void setCamposHabilitados(boolean habilitar) {
        txtNombre.setEnabled(habilitar);
        txtApellido.setEnabled(habilitar);
        txtTelefono.setEnabled(habilitar);
        txtCorreo.setEnabled(habilitar);
    }   

    /**
     * Creates new form FrmMantEntrenador
     */
    public FrmMantEntrenador() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Mantenimiento de Entrenador");
        
        // --- MAGIA DE FLATLAF: PLACEHOLDERS ---
        txtId.putClientProperty("JTextField.placeholderText", "Ej. 101");
        txtNombre.putClientProperty("JTextField.placeholderText", "Ej. Juan");
        txtApellido.putClientProperty("JTextField.placeholderText", "Ej. Pérez");
        txtTelefono.putClientProperty("JTextField.placeholderText", "Ej. 829-035-3412");
        txtCorreo.putClientProperty("JTextField.placeholderText", "ejemplo@correo.com");

        // --- VACIAR LOS CAMPOS PARA QUE SE VEA EL PLACEHOLDER ---
        txtId.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");

        // --- BLOQUEAR BOTONES AL INICIO ---
        aplicarEstadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnLimpiarCampos = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(614, 354));

        btnRegresar.setBackground(new java.awt.Color(204, 153, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de Entrenadores");

        jLabel2.setText("Cod. Entrenador *");

        txtId.setText("jTextField1");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(0, 153, 255));
        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre  *");

        txtNombre.setText("jTextField1");

        jLabel5.setText("Apellido *");

        txtApellido.setText("jTextField1");
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        jLabel6.setText("Correo");

        txtCorreo.setText("jTextField1");

        jLabel7.setText("Teléfono");

        txtTelefono.setText("jTextField1");
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRegresar)
                            .addGap(37, 37, 37)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(31, 31, 31)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnRegresar))
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(211, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idStr = txtId.getText().trim();
        if (idStr.isEmpty()) return;

        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar al entrenador ID: " + idStr + "?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) return;

        java.io.File archivo = new java.io.File("entrenadores.txt");
        java.util.List<String> lineasArchivo = new java.util.ArrayList<>();
        boolean encontrado = false;

        if (archivo.exists()) {
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                        // Rescatamos los datos y forzamos el estado a 0
                        String n = datos.length > 1 ? datos[1].trim() : "";
                        String a = datos.length > 2 ? datos[2].trim() : "";
                        String t = datos.length > 3 ? datos[3].trim() : "";
                        String c = datos.length > 4 ? datos[4].trim() : "";
                        lineasArchivo.add(idStr + "," + n + "," + a + "," + t + "," + c + ",0");
                        encontrado = true;
                    } else {
                        lineasArchivo.add(linea);
                    }
                }
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo: " + e.getMessage());
                return;
            }
        }

        if (encontrado) {
            try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(archivo))) {
                for (String l : lineasArchivo) {
                    pw.println(l);
                }
                JOptionPane.showMessageDialog(this, "Entrenador eliminado lógicamente.");
                limpiarCampos();
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String idStr = txtId.getText().trim();
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();

        // 1. Validar campos obligatorios (los que tienen asterisco en la imagen)
        if (idStr.isEmpty() || nombre.isEmpty() || apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los campos ID, Nombre y Apellido son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Validar el formato del teléfono (Formato República Dominicana: 10 dígitos)
        if (!telefono.isEmpty()) {
            // Eliminamos espacios y guiones para contar solo los números puros
            String numerosTelefono = telefono.replaceAll("[\\s-]", "");

            // Verificamos que solo sean números y que la longitud sea exactamente 10
            if (!numerosTelefono.matches("\\d+") || numerosTelefono.length() != 10) {
                JOptionPane.showMessageDialog(this, "El número de teléfono debe tener exactamente 10 dígitos.\nEjemplo válido: 829-035-3412", "Formato de Teléfono Incorrecto", JOptionPane.WARNING_MESSAGE);
                txtTelefono.requestFocus();
                return;
            }

            // (Opcional pero recomendado) Formateamos el texto automáticamente para guardarlo con los guiones
            // aunque el usuario lo haya escrito todo junto, ej: "8290353412" -> "829-035-3412"
            telefono = numerosTelefono.substring(0, 3) + "-" + numerosTelefono.substring(3, 6) + "-" + numerosTelefono.substring(6, 10);
        }

        // 2. Validar correo si el usuario escribió algo (igual que en usuarios)
        if (!correo.isEmpty()) {
            String regexCorreo = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
            if (!correo.matches(regexCorreo)) {
                JOptionPane.showMessageDialog(this, "El formato del correo es inválido.", "Formato Incorrecto", JOptionPane.WARNING_MESSAGE);
                txtCorreo.requestFocus();
                return;
            }
        }

        java.io.File archivo = new java.io.File("entrenadores.txt");
        java.util.List<String> lineasArchivo = new java.util.ArrayList<>();

        if (archivo.exists()) {
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                        if (!esNuevoEntrenador) {
                            // Actualiza y mantiene el estado 1 (Activo)
                            lineasArchivo.add(idStr + "," + nombre + "," + apellido + "," + telefono + "," + correo + ",1");
                        }
                    } else {
                        lineasArchivo.add(linea);
                    }
                }
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo: " + e.getMessage());
            }
        }

        if (esNuevoEntrenador) {
            // Evitar duplicados
            for (String l : lineasArchivo) {
                String[] datos = l.split(",", -1);
                if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                    JOptionPane.showMessageDialog(this, "El ID de entrenador ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            // Agrega nuevo con estado 1
            lineasArchivo.add(idStr + "," + nombre + "," + apellido + "," + telefono + "," + correo + ",1");
        }

        try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(archivo))) {
            for (String l : lineasArchivo) {
                pw.println(l);
            }
            JOptionPane.showMessageDialog(this, "Datos guardados correctamente.");
            limpiarCampos();
        } catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        String idStr = txtId.getText().trim();
        if (idStr.isEmpty()) {
            setCamposHabilitados(false);
            return;
        }

        // Validar que sea un entero válido
        try {
            Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del Entrenador debe ser un número entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtId.setText("");
            setCamposHabilitados(false);
            txtId.requestFocus();
            return;
        }

        java.io.File archivo = new java.io.File("entrenadores.txt");
        boolean encontrado = false;
        String nombre = "", apellido = "", telefono = "", correo = "", estado = "1";

        if (archivo.exists()) {
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length >= 3 && datos[0].trim().equals(idStr)) {
                        encontrado = true;
                        nombre = datos[1].trim();
                        apellido = datos[2].trim();
                        telefono = datos.length > 3 ? datos[3].trim() : "";
                        correo = datos.length > 4 ? datos[4].trim() : "";
                        estado = datos.length > 5 ? datos[5].trim() : "1";
                        break;
                    }
                }
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this, "Error al buscar el entrenador: " + e.getMessage());
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "El entrenador es NUEVO y se está creando.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            esNuevoEntrenador = true;

            // Habilitar campos de texto y botones para nuevo registro
            setCamposHabilitados(true);
            btnGuardar.setEnabled(true);
            btnLimpiarCampos.setEnabled(true);
            btnEliminar.setEnabled(false);

            txtNombre.requestFocus();
        } else {
            if (estado.equals("0")) {
                JOptionPane.showMessageDialog(this, "Este entrenador se encuentra ELIMINADO/INACTIVO.\nNo es posible modificarlo.", "Inactivo", JOptionPane.ERROR_MESSAGE);
                limpiarCampos();
                return;
            }

            JOptionPane.showMessageDialog(this, "El entrenador ya EXISTE y se está modificando.", "Aviso", JOptionPane.WARNING_MESSAGE);
            esNuevoEntrenador = false;

            txtNombre.setText(nombre);
            txtApellido.setText(apellido);
            txtTelefono.setText(telefono);
            txtCorreo.setText(correo);

            // Habilitar campos de texto y todos los botones para edición
            setCamposHabilitados(true);
            btnGuardar.setEnabled(true);
            btnLimpiarCampos.setEnabled(true);
            btnEliminar.setEnabled(true);

            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMantEntrenador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
