/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author yefry
 */
public class FrmMantCliente extends javax.swing.JFrame {

    private boolean esNuevoCliente = true;
    private final SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");

    // Método que bloquea los botones cuando no hay datos activos y resetea campos por defecto
    private void aplicarEstadoInicial() {
        btnGuardar.setEnabled(false);
        btnLimpiarCampos.setEnabled(false);
        btnEliminar.setEnabled(false);
        esNuevoCliente = true;

        // Bloquear todos los campos de entrada
        setCamposHabilitados(false);

        // La Fecha de Ingreso se toma del sistema por defecto
        txtFechaIngreso.setText(formatoFecha.format(new Date()));
        txtFechaIngreso.setEditable(false);

        // El Balance por defecto es 0
        txtBalance.setText("0.0");
        txtBalance.setEditable(false);
    }

    // Método para limpiar la pantalla y devolverla al estado base
    private void limpiarCampos() {
        txtIdCliente.setText("");
        txtNombre.setText("");
        txtApPat.setText("");
        txtApMat.setText("");
        txtDireccion.setText("");
        jdFechaNac.setDate(null); // Limpiar el JDateChooser
        txtTelefono.setText("");
        txtCelular.setText("");
        cbStatus.setSelectedIndex(0);
        cbTipo.setSelectedIndex(0);
        txtCorreo.setText("");
        txtCuota.setText("");
        
        txtIdCliente.requestFocus();
        aplicarEstadoInicial();
    }
    
    private void setCamposHabilitados(boolean habilitar) {
    txtNombre.setEnabled(habilitar);
    txtApPat.setEnabled(habilitar);
    txtApMat.setEnabled(habilitar);
    txtDireccion.setEnabled(habilitar);
    jdFechaNac.setEnabled(habilitar);
    txtTelefono.setEnabled(habilitar);
    txtCelular.setEnabled(habilitar);
    cbStatus.setEnabled(habilitar);
    cbTipo.setEnabled(habilitar);
    txtCorreo.setEnabled(habilitar);
    txtCuota.setEnabled(habilitar);
    }

    /**
     * Creates new form FrmMantCliente
     */
    public FrmMantCliente() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Mantenimiento de Cliente");
        
        // --- MAGIA DE FLATLAF: PLACEHOLDERS ---
        txtIdCliente.putClientProperty("JTextField.placeholderText", "Ej. 1001");
        txtNombre.putClientProperty("JTextField.placeholderText", "Ej. Juan");
        txtApPat.putClientProperty("JTextField.placeholderText", "Ej. Pérez");
        txtApMat.putClientProperty("JTextField.placeholderText", "Ej. Rodríguez");
        txtDireccion.putClientProperty("JTextField.placeholderText", "Ej. Calle Sol #4");
        txtTelefono.putClientProperty("JTextField.placeholderText", "Ej. 829-035-3412");
        txtCelular.putClientProperty("JTextField.placeholderText", "Ej. 809-555-4321");
        txtCorreo.putClientProperty("JTextField.placeholderText", "ejemplo@correo.com");
        txtCuota.putClientProperty("JTextField.placeholderText", "Ej. 1500.00");

        // Llenar ComboBoxes de forma predeterminada
        cbStatus.removeAllItems();
        cbStatus.addItem("Activo");
        cbStatus.addItem("Pasivo");
        
        cbTipo.removeAllItems();
        cbTipo.addItem("Socio Activo");
        cbTipo.addItem("Invitado");

        limpiarCampos();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jdFechaNac = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        txtApPat = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        btnLimpiarCampos = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtCuota = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        txtIdCliente = new javax.swing.JTextField();
        txtFechaIngreso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtApMat = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de Clientes");

        btnRegresar.setBackground(new java.awt.Color(204, 153, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel21.setText("Apellido Paterno *");

        txtApPat.setText("jTextField1");

        jLabel22.setText("Dirección *");

        txtDireccion.setText("jTextField1");

        jLabel23.setText("Teléfono *");

        txtTelefono.setText("jTextField1");

        jLabel24.setText("Celular *");

        txtCelular.setText("jTextField1");

        jLabel25.setText("Balance");

        txtBalance.setText("jTextField1");
        txtBalance.setEnabled(false);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Pasivo" }));

        btnLimpiarCampos.setBackground(new java.awt.Color(0, 153, 255));
        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel26.setText("Status *");

        txtCuota.setText("jTextField1");

        jLabel27.setText("Correo Electrónico");

        txtCorreo.setText("jTextField1");

        jLabel28.setText("Tipo de Cliente *");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Socio", "Invitado" }));

        txtIdCliente.setText("jTextField1");
        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        txtFechaIngreso.setText("jTextField1");
        txtFechaIngreso.setEnabled(false);

        jLabel8.setText("Cod. Cliente *");

        jLabel30.setText("Fecha Ingreso (AUTO)");

        txtNombre.setText("jTextField1");

        jLabel31.setText("Fecha de Nacimiento *");

        jLabel19.setText("Nombre *");

        txtApMat.setText("jTextField1");

        jLabel20.setText("Apellido Materno *");

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel29.setText("Valor de Cuota *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnRegresar)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(54, 54, 54))
                                    .addComponent(jLabel19))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdCliente)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApMat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jdFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCuota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(txtApPat))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegresar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtApPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String idStr = txtIdCliente.getText().trim();
        String nombre = txtNombre.getText().trim();
        String apPat = txtApPat.getText().trim();
        String apMat = txtApMat.getText().trim();
        String direccion = txtDireccion.getText().trim();
        Date fechaNacDate = jdFechaNac.getDate();
        String telefono = txtTelefono.getText().trim();
        String celular = txtCelular.getText().trim();
        String fechaIngreso = txtFechaIngreso.getText().trim();
        
        String status = cbStatus.getSelectedItem().toString(); // Activo o Pasivo
        String tipo = cbTipo.getSelectedItem().toString(); // Socio Activo o Invitado
        
        String correo = txtCorreo.getText().trim();
        String balance = txtBalance.getText().trim();
        String cuota = txtCuota.getText().trim();

        // 1. Validar campos obligatorios marcados con (*)
        if (idStr.isEmpty() || nombre.isEmpty() || apPat.isEmpty() || apMat.isEmpty() || 
            direccion.isEmpty() || fechaNacDate == null || telefono.isEmpty() || celular.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos con asterisco (*) son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. REQUISITO: "Los tipos socios son los únicos que pueden ser activos"
        if (tipo.equals("Invitado") && status.equals("Activo")) {
            JOptionPane.showMessageDialog(this, "Un Cliente tipo 'Invitado' NO puede tener el status 'Activo'.\nSolo los 'Socios' pueden ser activos.", "Regla de Negocio", JOptionPane.WARNING_MESSAGE);
            cbStatus.requestFocus();
            return;
        }

        // Formatear Fecha de Nacimiento a String
        String fechaNacStr = formatoFecha.format(fechaNacDate);

        // 3. Validar el formato de los teléfonos (República Dominicana: 10 dígitos)
        String[] telefonosAValidar = {telefono, celular};
        for (String tel : telefonosAValidar) {
            String numerosTel = tel.replaceAll("[\\s-]", "");
            if (!numerosTel.matches("\\d+") || numerosTel.length() != 10) {
                JOptionPane.showMessageDialog(this, "El teléfono y celular deben tener exactamente 10 dígitos.\nEjemplo: 829-035-3412", "Formato Incorrecto", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        // Aplicar formato estándar con guiones para guardar limpio
        telefono = telefono.replaceAll("[\\s-]", "").replaceAll("(\\d{3})(\\d{3})(\\d{4})", "$1-$2-$3");
        celular = celular.replaceAll("[\\s-]", "").replaceAll("(\\d{3})(\\d{3})(\\d{4})", "$1-$2-$3");

        // Setear Cuota vacía a "0.0" por seguridad en el archivo
        if (cuota.isEmpty()) cuota = "0.0";

        // Preparar la línea de registro (El último "1" indica que el registro está vivo/activo lógicamente)
        String lineaRegistro = idStr + "," + nombre + "," + apPat + "," + apMat + "," + 
                               direccion + "," + fechaNacStr + "," + telefono + "," + 
                               celular + "," + fechaIngreso + "," + status + "," + 
                               tipo + "," + correo + "," + balance + "," + cuota + ",1";

        File archivo = new File("clientes.txt");
        List<String> lineasArchivo = new ArrayList<>();

        if (archivo.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                        if (!esNuevoCliente) {
                            lineasArchivo.add(lineaRegistro); // Actualiza la línea
                        }
                    } else {
                        lineasArchivo.add(linea); // Mantiene las demás
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo: " + e.getMessage());
            }
        }

        if (esNuevoCliente) {
            // Evitar duplicados
            for (String l : lineasArchivo) {
                String[] datos = l.split(",", -1);
                if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                    JOptionPane.showMessageDialog(this, "El ID del cliente ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            lineasArchivo.add(lineaRegistro);
        }

        // Guardar archivo
        try (PrintWriter pw = new PrintWriter(new FileWriter(archivo))) {
            for (String l : lineasArchivo) {
                pw.println(l);
            }
            JOptionPane.showMessageDialog(this, "Cliente guardado exitosamente.");
            limpiarCampos();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idStr = txtIdCliente.getText().trim();
        if (idStr.isEmpty()) return;
        
        // REQUISITO: Validar Balance antes de eliminar
        try {
            double balanceActual = Double.parseDouble(txtBalance.getText().trim());
            if (balanceActual > 0) {
                JOptionPane.showMessageDialog(this, "Un Cliente con Balance mayor que Cero no se puede borrar.\nBalance actual: RD$ " + balanceActual, "Acción Denegada", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            // Si el balance está corrupto, evitamos la eliminación por seguridad
            JOptionPane.showMessageDialog(this, "Error al leer el balance del cliente.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar al cliente ID: " + idStr + "?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) return;

        File archivo = new File("clientes.txt");
        List<String> lineasArchivo = new ArrayList<>();
        boolean encontrado = false;

        if (archivo.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length >= 15 && datos[0].trim().equals(idStr)) {
                        // Rescatar datos y cambiar SOLO el índice final (estadoRegistro) a 0
                        datos[14] = "0"; 
                        lineasArchivo.add(String.join(",", datos));
                        encontrado = true;
                    } else {
                        lineasArchivo.add(linea);
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo: " + e.getMessage());
                return;
            }
        }

        if (encontrado) {
            try (PrintWriter pw = new PrintWriter(new FileWriter(archivo))) {
                for (String l : lineasArchivo) {
                    pw.println(l);
                }
                JOptionPane.showMessageDialog(this, "Cliente eliminado lógicamente del sistema.");
                limpiarCampos();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar archivo: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        String idStr = txtIdCliente.getText().trim();
        if (idStr.isEmpty()) {
            setCamposHabilitados(false);
            return;
        }

        // Validar que sea numérico
        try {
            Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del Cliente debe ser numérico.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdCliente.setText("");
            setCamposHabilitados(false);
            txtIdCliente.requestFocus();
            return;
        }

        File archivo = new File("clientes.txt");
        boolean encontrado = false;
        String[] datosCliente = null;

        if (archivo.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length >= 15 && datos[0].trim().equals(idStr)) {
                        encontrado = true;
                        datosCliente = datos;
                        break;
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al buscar cliente: " + e.getMessage());
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "El cliente no existe. Ingrese los datos para registrarlo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            esNuevoCliente = true;

            // Habilitar campos y botones para nuevo registro
            setCamposHabilitados(true);
            btnGuardar.setEnabled(true);
            btnLimpiarCampos.setEnabled(true);
            btnEliminar.setEnabled(false);

            txtNombre.requestFocus();
        } else {
            // Verificar si está eliminado lógicamente (índice 14 = estadoRegistro 0)
            if (datosCliente[14].trim().equals("0")) {
                JOptionPane.showMessageDialog(this, "Este cliente se encuentra ELIMINADO.", "Aviso", JOptionPane.WARNING_MESSAGE);
                setCamposHabilitados(false);
                btnGuardar.setEnabled(false);
                btnEliminar.setEnabled(false);
                return;
            }

            // Cargar datos del cliente encontrado
            txtNombre.setText(datosCliente[1]);
            txtApPat.setText(datosCliente[2]);
            txtApMat.setText(datosCliente[3]);
            txtDireccion.setText(datosCliente[4]);

            try {
                jdFechaNac.setDate(formatoFecha.parse(datosCliente[5]));
            } catch (Exception e) {
                jdFechaNac.setDate(null);
            }

            txtTelefono.setText(datosCliente[6]);
            txtCelular.setText(datosCliente[7]);
            txtFechaIngreso.setText(datosCliente[8]);
            cbStatus.setSelectedItem(datosCliente[9]);
            cbTipo.setSelectedItem(datosCliente[10]);
            txtCorreo.setText(datosCliente[11]);
            txtBalance.setText(datosCliente[12]);
            txtCuota.setText(datosCliente[13]);

            esNuevoCliente = false;

            // Habilitar campos y controles para edición/eliminación
            setCamposHabilitados(true);
            btnGuardar.setEnabled(true);
            btnLimpiarCampos.setEnabled(true);
            btnEliminar.setEnabled(true);

            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_txtIdClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMantCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser jdFechaNac;
    private javax.swing.JTextField txtApMat;
    private javax.swing.JTextField txtApPat;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
