/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
/**
 *
 * @author yefry
 */
public class FrmMantActividad extends javax.swing.JFrame {

    private boolean esNuevaActividad = true;

    // Método que bloquea los botones cuando no hay datos activos
    private void aplicarEstadoInicial() {
        btnGuardar.setEnabled(false);
        btnLimpiarCampos.setEnabled(false); 
        btnEliminar.setEnabled(false);
        esNuevaActividad = true;
    }

    // Método para limpiar la pantalla y devolverla al estado base
    private void limpiarCampos() {
        txtIdAct.setText("");
        txtNombreAct.setText("");
        txtDescripcionAct.setText("");
        txtIdLocalizacionAct.setText("");
        txtIdEntrenadorAct.setText("");
        
        txtIdAct.requestFocus();
        aplicarEstadoInicial();
    }
    
    private void aplicarFiltrosNumericos() {
        // Filtro 1: Solo números enteros (para Código de Cuota y Código de Cliente)
        DocumentFilter filtroEnteros = new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (string != null && string.matches("\\d+")) {
                    super.insertString(fb, offset, string, attr);
                }
            }
            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text != null && text.matches("\\d*")) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        };

        // Aplicar Filtro 1 a los campos de códigos
        ((AbstractDocument) txtIdAct.getDocument()).setDocumentFilter(filtroEnteros);
        ((AbstractDocument) txtIdLocalizacionAct.getDocument()).setDocumentFilter(filtroEnteros);
    }


    // Constructor de la ventana
    public FrmMantActividad() {
        initComponents();
        setLocationRelativeTo(null);
        aplicarFiltrosNumericos(); 
        setTitle("Mantenimiento de Actividades");
        
        // --- MAGIA DE FLATLAF: PLACEHOLDERS ---
        txtIdAct.putClientProperty("JTextField.placeholderText", "Ej. 1");
        txtNombreAct.putClientProperty("JTextField.placeholderText", "Ej. Yoga Matutino");
        txtDescripcionAct.putClientProperty("JTextField.placeholderText", "Ej. Clase de relajación y estiramiento");
        txtIdLocalizacionAct.putClientProperty("JTextField.placeholderText", "Ej. 10");
        txtIdEntrenadorAct.putClientProperty("JTextField.placeholderText", "Ej. 5");

        // --- VACIAR LOS CAMPOS PARA QUE SE VEA EL PLACEHOLDER ---
        txtIdAct.setText("");
        txtNombreAct.setText("");
        txtDescripcionAct.setText("");
        txtIdLocalizacionAct.setText("");
        txtIdEntrenadorAct.setText("");

        // --- BLOQUEAR BOTONES AL INICIO ---
        aplicarEstadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtDescripcionAct = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        txtIdLocalizacionAct = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdAct = new javax.swing.JTextField();
        btnLimpiarCampos = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombreAct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIdEntrenadorAct = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Descripción  *");

        txtDescripcionAct.setText("jTextField1");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de Actividades");

        jLabel3.setText("Cod. Localización *");

        btnRegresar.setBackground(new java.awt.Color(204, 153, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        txtIdLocalizacionAct.setText("jTextField1");
        txtIdLocalizacionAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLocalizacionActActionPerformed(evt);
            }
        });

        jLabel2.setText("Cod. Actividad *");

        txtIdAct.setText("jTextField1");
        txtIdAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(0, 153, 255));
        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre  *");

        txtNombreAct.setText("jTextField1");

        jLabel6.setText("Cod. Entrenador *");

        txtIdEntrenadorAct.setText("jTextField1");
        txtIdEntrenadorAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEntrenadorActActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIdAct)
                                .addComponent(txtIdLocalizacionAct, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNombreAct, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIdEntrenadorAct))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(58, 58, 58)
                            .addComponent(txtDescripcionAct))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtIdEntrenadorAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtIdLocalizacionAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescripcionAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnLimpiarCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtIdLocalizacionActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLocalizacionActActionPerformed
        String idLocStr = txtIdLocalizacionAct.getText().trim();
        if (idLocStr.isEmpty()) return;

        try {
            Integer.parseInt(idLocStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Localización debe ser un número entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdLocalizacionAct.setText("");
            txtIdLocalizacionAct.requestFocus();
            return;
        }

        File archivoLocalizaciones = new File("localizaciones.txt");
        boolean localizacionExiste = false;

        if (archivoLocalizaciones.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivoLocalizaciones))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idLocStr)) {
                        String estadoLoc = datos.length > 2 ? datos[2].trim() : "1";
                        if (estadoLoc.equals("1")) {
                            localizacionExiste = true;
                            break;
                        }
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al verificar la localización: " + e.getMessage());
            }
        }

        if (!localizacionExiste) {
            JOptionPane.showMessageDialog(this, "El ID de Localización ingresado NO existe o se encuentra inactivo.", "Error de Referencia", JOptionPane.ERROR_MESSAGE);
            txtIdLocalizacionAct.setText("");
            txtIdLocalizacionAct.requestFocus();
        } else {
            txtIdEntrenadorAct.requestFocus();
        }
    }//GEN-LAST:event_txtIdLocalizacionActActionPerformed

    private void txtIdActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActActionPerformed
        String idStr = txtIdAct.getText().trim();
        if (idStr.isEmpty()) return;

        // Validar que el ID sea un número entero
        try {
            Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de la Actividad debe ser un número entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdAct.setText("");
            txtIdAct.requestFocus();
            return;
        }

        File archivo = new File("actividades.txt");
        boolean encontrado = false;
        String nombre = "", descripcion = "", idLocalizacion = "", idEntrenador = "", estado = "1";

        if (archivo.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    // Estructura: Id_Act, Nombre_Act, Descripcion_Act, Id_Localizacion_Act, Id_Entrenador_Act, Estado
                    if (datos.length >= 5 && datos[0].trim().equals(idStr)) {
                        encontrado = true;
                        nombre = datos[1].trim();
                        descripcion = datos[2].trim();
                        idLocalizacion = datos[3].trim();
                        idEntrenador = datos[4].trim();
                        estado = datos.length > 5 ? datos[5].trim() : "1";
                        break;
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al buscar la actividad: " + e.getMessage());
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Creando...", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            esNuevaActividad = true;
            
            btnGuardar.setEnabled(true);
            btnLimpiarCampos.setEnabled(true);
            btnEliminar.setEnabled(false);
            
            txtNombreAct.requestFocus();
        } else {
            if (estado.equals("0")) {
                JOptionPane.showMessageDialog(this, "Esta actividad se encuentra ELIMINADA/INACTIVA.\nNo es posible modificarla.", "Inactivo", JOptionPane.ERROR_MESSAGE);
                limpiarCampos();
                return;
            }

            JOptionPane.showMessageDialog(this, "Modificando...", "Aviso", JOptionPane.WARNING_MESSAGE);
            esNuevaActividad = false;
            
            txtNombreAct.setText(nombre);
            txtDescripcionAct.setText(descripcion);
            txtIdLocalizacionAct.setText(idLocalizacion);
            txtIdEntrenadorAct.setText(idEntrenador);

            btnGuardar.setEnabled(true);
            btnLimpiarCampos.setEnabled(true);
            btnEliminar.setEnabled(true);
            
            txtNombreAct.requestFocus();
        }
    }//GEN-LAST:event_txtIdActActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String idStr = txtIdAct.getText().trim();
        String nombre = txtNombreAct.getText().trim();
        String descripcion = txtDescripcionAct.getText().trim();
        String idLocStr = txtIdLocalizacionAct.getText().trim();
        String idEntStr = txtIdEntrenadorAct.getText().trim();

        // 1. Validar atributos obligatorios
        if (idStr.isEmpty() || nombre.isEmpty() || descripcion.isEmpty() || idLocStr.isEmpty() || idEntStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Integer.parseInt(idLocStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Localización debe ser un número entero válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdLocalizacionAct.requestFocus();
            return;
        }

        try {
            Integer.parseInt(idEntStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Entrenador debe ser un número entero válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdEntrenadorAct.requestFocus();
            return;
        }

        // 2. VALIDAR QUE EL ID DE LOCALIZACIÓN EXISTA Y ESTÉ ACTIVO
        File archivoLocalizaciones = new File("localizaciones.txt");
        boolean localizacionExiste = false;

        if (archivoLocalizaciones.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivoLocalizaciones))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idLocStr)) {
                        String estadoLoc = datos.length > 2 ? datos[2].trim() : "1";
                        if (estadoLoc.equals("1")) {
                            localizacionExiste = true;
                            break;
                        }
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al verificar la localización: " + e.getMessage());
                return;
            }
        }

        if (!localizacionExiste) {
            JOptionPane.showMessageDialog(this, "El ID de Localización especificado NO existe o se encuentra inactivo.", "Error de Referencia", JOptionPane.ERROR_MESSAGE);
            txtIdLocalizacionAct.requestFocus();
            return;
        }

        // 3. VALIDAR QUE EL ID DE ENTRENADOR EXISTA Y ESTÉ ACTIVO
        File archivoEntrenadores = new File("entrenadores.txt");
        boolean entrenadorExiste = false;

        if (archivoEntrenadores.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivoEntrenadores))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idEntStr)) {
                        String estadoEnt = datos.length > 0 ? datos[datos.length - 1].trim() : "1";
                        if (estadoEnt.equals("1")) {
                            entrenadorExiste = true;
                            break;
                        }
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al verificar el entrenador: " + e.getMessage());
                return;
            }
        }

        if (!entrenadorExiste) {
            JOptionPane.showMessageDialog(this, "El ID de Entrenador especificado NO existe o se encuentra inactivo.", "Error de Referencia", JOptionPane.ERROR_MESSAGE);
            txtIdEntrenadorAct.requestFocus();
            return;
        }

        // 4. Guardar en actividades.txt
        File archivo = new File("actividades.txt");
        List<String> lineasArchivo = new ArrayList<>();

        if (archivo.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                        if (!esNuevaActividad) {
                            // Actualiza manteniendo el estado activo (1)
                            lineasArchivo.add(idStr + "," + nombre + "," + descripcion + "," + idLocStr + "," + idEntStr + ",1");
                        }
                    } else {
                        lineasArchivo.add(linea);
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo de actividades: " + e.getMessage());
            }
        }

        if (esNuevaActividad) {
            for (String l : lineasArchivo) {
                String[] datos = l.split(",", -1);
                if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                    JOptionPane.showMessageDialog(this, "El ID de esta actividad ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            // Agrega nueva actividad con estado activo (1)
            lineasArchivo.add(idStr + "," + nombre + "," + descripcion + "," + idLocStr + "," + idEntStr + ",1");
        }

        try (PrintWriter pw = new PrintWriter(new FileWriter(archivo))) {
            for (String l : lineasArchivo) {
                pw.println(l);
            }
            JOptionPane.showMessageDialog(this, "Actividad guardada correctamente.");
            limpiarCampos();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar actividad: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idStr = txtIdAct.getText().trim();
        if (idStr.isEmpty()) return;

        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar la actividad ID: " + idStr + "?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) return;

        File archivo = new File("actividades.txt");
        List<String> lineasArchivo = new ArrayList<>();
        boolean encontrado = false;

        if (archivo.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idStr)) {
                        String nom = datos.length > 1 ? datos[1].trim() : "";
                        String desc = datos.length > 2 ? datos[2].trim() : "";
                        String idLoc = datos.length > 3 ? datos[3].trim() : "";
                        String idEnt = datos.length > 4 ? datos[4].trim() : "";
                        // Cambiar estado a inactivo (0)
                        lineasArchivo.add(idStr + "," + nom + "," + desc + "," + idLoc + "," + idEnt + ",0");
                        encontrado = true;
                    } else {
                        lineasArchivo.add(linea);
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer archivo: " + e.getMessage());
                return;
            }
        }

        if (encontrado) {
            try (PrintWriter pw = new PrintWriter(new FileWriter(archivo))) {
                for (String l : lineasArchivo) {
                    pw.println(l);
                }
                JOptionPane.showMessageDialog(this, "Actividad eliminada lógicamente.");
                limpiarCampos();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtIdEntrenadorActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEntrenadorActActionPerformed
        String idEntStr = txtIdEntrenadorAct.getText().trim();
        if (idEntStr.isEmpty()) return;

        try {
            Integer.parseInt(idEntStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Entrenador debe ser un número entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdEntrenadorAct.setText("");
            txtIdEntrenadorAct.requestFocus();
            return;
        }

        File archivoEntrenadores = new File("entrenadores.txt");
        boolean entrenadorExiste = false;

        if (archivoEntrenadores.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivoEntrenadores))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(",", -1);
                    if (datos.length > 0 && datos[0].trim().equals(idEntStr)) {
                        String estadoEnt = datos.length > 0 ? datos[datos.length - 1].trim() : "1";
                        if (estadoEnt.equals("1")) {
                            entrenadorExiste = true;
                            break;
                        }
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al verificar el entrenador: " + e.getMessage());
            }
        }

        if (!entrenadorExiste) {
            JOptionPane.showMessageDialog(this, "El ID de Entrenador ingresado NO existe o se encuentra inactivo.", "Error de Referencia", JOptionPane.ERROR_MESSAGE);
            txtIdEntrenadorAct.setText("");
            txtIdEntrenadorAct.requestFocus();
        } else {
            txtDescripcionAct.requestFocus();
        }
    }//GEN-LAST:event_txtIdEntrenadorActActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMantActividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField txtDescripcionAct;
    public javax.swing.JTextField txtIdAct;
    public javax.swing.JTextField txtIdEntrenadorAct;
    public javax.swing.JTextField txtIdLocalizacionAct;
    public javax.swing.JTextField txtNombreAct;
    // End of variables declaration//GEN-END:variables
}
